# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Build
      run: go build -v ./src/backend

    - name: go-test-report
      uses: brian-pickens/go-test-report@v1
      with:
        packages: ./src/backend # optional, default is ./...
        reports_only: false # optional, default is false
        summary: true # optional, default is true
        GO111MODULE: auto # optional, default is auto
          
