name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'
    - name: Install dependencies
      run: go get ./src/backend
    - name: Build
      run: go build -v ./src/backend
    - name: Test with the Go CLI
      run: go test -v ./src/backend
    - name: Upload Go test results
      uses: actions/upload-artifact@v4
      with:
        name: Go-results-1.23
        path: TestResults-1.23.json
